In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


## 2022.06.09 - Tensorflow Fundamental 1

### Tensorflow Constant
- scalar: 0 ndim
- vector
- matrix:
- tensor

In [ ]:
scalar = tf.constant(3)
print(scalar)
print(scalar.ndim)

tf.Tensor(3, shape=(), dtype=int32)
0


In [ ]:
vector = tf.constant([10,10],dtype=tf.dtypes.int32)
print(vector.ndim)
print(vector)

1
tf.Tensor([10 10], shape=(2,), dtype=int32)


In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]],dtype=tf.dtypes.float16)
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 7. 10.]], shape=(2, 2), dtype=float16)
2


In [ ]:
tensor = tf.constant([[[10,10,10],
                               [7,6,6]],      
                              [[10,10,10],
                               [7,6,6]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[10 10 10]
  [ 7  6  6]]

 [[10 10 10]
  [ 7  6  6]]], shape=(2, 2, 3), dtype=int32)
3


In [ ]:
tensor[0,0,0] = 2
tensor[0,0,0].assign(2)

TypeError: ignored

In [ ]:
tf.reshape(tensor,shape=(3,2,2))

### Tensorflow Variables
- can change data through assign method --> inplace operations
- if value is in multidimensional matrix --> then the index of value need to be in the same []

In [ ]:
a = tf.Variable([[1,2],[3,4]])
#a[0][0] = 99
a[0,0].assign(99) # assign -> inplace operations

### Random Tensors
- usually used in the weights and bias in the neural networks

In [ ]:
# create generator with same random seed
random_1 = tf.random.Generator.from_seed(20)

# use this generator to generate the random number
random_1 = random_1.normal((100,100))
random_2 = tf.random.Generator.from_seed(20)
random_2 = random_2.normal((100,100))
print(random_1)
print(random_2)
random_1 == random_2

In [ ]:
tf.math.reduce_std(a[:,:])

### Shuffle Tensors
- in order to evenly learn the pattern from the shuffled data.
- if the data in training dataset is systematic then learning might tend to be just one main kind of dataset. 
  - The model performance might be bad.

In [ ]:
tf.random.set_seed(20)
prev_tensors = tf.constant([[10,20],
                            [30,3],
                            [2,5]])
print(prev_tensors)
shuffled_tensors = tf.random.shuffle(prev_tensors)
print(shuffled_tensors)

tf.Tensor(
[[10 20]
 [30  3]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [ 2  5]
 [30  3]], shape=(3, 2), dtype=int32)


### Convert numpy arrays to Tensorflow tensor
- the tensorflow is similar to numpy in the viewpoint of numerical computation
- the different between them is tensorflow tensors can be run on the GPU
- numpy -> tensorflow: numpy data can be the input of tensorflow functiion
- tensorflow -> numpy: tensor.numpy()

In [ ]:
tf_ones = tf.ones([10,7])
np_ones = np.ones([10,7])

In [ ]:
numpy_a = np.arange(1,11).reshape(2,5)
tensor_a = tf.constant(numpy_a,shape=(5,2))

In [ ]:
print(tensor_a)
print(numpy_a)

### Tensor Attributes
- size: element 數量
- shape, rank
- ndim: n axis => only applied to constant, variable didn't have this prop
- multi index getter

In [ ]:
a = tf.Variable([[10,20],[30,40]])

In [ ]:
print("Shape: ", a.shape)
print("TF.Shape: ", tf.shape(a))

# tensors getter with multtiple index
print(a[0,0])
print(a[:,1])

 # shape of tensors
print("Rank: ", tf.rank(a))

# datatype of tensor
print("Datatype: ",a.dtype)

# size is count of element 
print("Size:", tf.size(input=a).numpy())

In [ ]:
a.numpy()

---

## 2022.06.10 - Tensorflow Fundamental 2

### Indexing and Expanding Tensors
- expand dim: add on the axis -> tf.newaxis
- n dim -> n 組 middle bracket

In [ ]:
tensor = tf.zeros(shape=(2,3,4,5))
tensor[0,0,0,:]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
tf.reshape(tensor,shape=(10,12))

<tf.Tensor: shape=(10, 12), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor[:,:,tf.newaxis]

# ... mean all axis which is same as above one expression
rank_2_tensor[...,tf.newaxis]

tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulate Tensors
- Tensors Basic Operations
- matrix multiplication
  - tensorflow: tf.matmul
  - python: @
  - reshape != transpose, reshape is kind of like the shuffle instead of transpose
- dot 

In [ ]:
# element-wise operation through python operation
a = tf.constant([[1,2],[5,6]],dtype=tf.dtypes.float16)
print(a+10)
print(a*10)
print(a%10)
print(a-10)

tf.Tensor(
[[11. 12.]
 [15. 16.]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[10. 20.]
 [50. 60.]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[1. 2.]
 [5. 6.]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[-9. -8.]
 [-5. -4.]], shape=(2, 2), dtype=float16)


In [ ]:
# use tenworflow built-in function to do the operations, element-wise oprations
print(tf.matmul(a,tf.transpose(a)))

# matrix multiplication in python operation is at sign @
print(a @ tf.transpose(a))

tf.Tensor(
[[ 5. 17.]
 [17. 61.]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[ 5. 17.]
 [17. 61.]], shape=(2, 2), dtype=float16)


In [ ]:
b = tf.constant([[1,2,3],[4,5,6]])
b, tf.reshape(b,shape=(3,2)), tf.transpose(b)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [ ]:
#Either a scalar N, or a list or an int32 Tensor of shape [2, k]. 
# If axes is a scalar, sum over the 'last' N axes of a and the 'first' N axes of b in order. 
tf.tensordot(tf.transpose(b),b,1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

### Tenworflow DataType Change

In [ ]:
tensor = tf.constant([[1.2,2],[3,4]])

In [ ]:
tf.cast(x=tensor, dtype=tf.dtypes.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2, 2. ],
       [3. , 4. ]], dtype=float32)>

In [ ]:
tf.cast(tensor,dtype=tf.dtypes.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Tensorflow Aggregation Function

In [ ]:
data = tf.constant(np.random.randint(0,100,size=50)*1.0)

In [ ]:
print(tf.abs(data))
print(tf.math.reduce_mean(data))
print(tf.math.reduce_min(data))
print(tf.math.reduce_max(data))
print(tf.math.reduce_sum(data))
print(tf.math.reduce_std(data))
print(tf.math.reduce_variance(data))
print(tf.math.sqrt(tf.math.reduce_variance(data)))


tf.Tensor(
[43. 24.  1. 28. 70. 85. 81. 50. 72. 66. 19. 26. 24. 85. 29. 10. 93. 66.
 69. 60. 11. 69. 78.  5. 56. 18. 42. 50. 47. 35.  5. 79. 24. 35. 75. 43.
  4. 36. 91. 19. 80. 30. 87.  6. 36. 52. 99. 91. 67. 90.], shape=(50,), dtype=float64)
tf.Tensor(49.22, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(99.0, shape=(), dtype=float64)
tf.Tensor(2461.0, shape=(), dtype=float64)
tf.Tensor(28.695149415885602, shape=(), dtype=float64)
tf.Tensor(823.4115999999999, shape=(), dtype=float64)
tf.Tensor(28.695149415885602, shape=(), dtype=float64)


In [ ]:
data_mean = tf.math.reduce_mean(data)
delta_sum = tf.reduce_sum(tf.math.pow(data - data_mean, 2))
#data_size = data.shape[0]
# use cast to convert the data type so that we can run the basic operation on tensors
data_size = tf.cast(tf.size(data),dtype=tf.dtypes.float64)
data_variance = tf.divide(delta_sum,data_size)
print("variance:", data_variance)
tf.sqrt(data_variance)

variance: tf.Tensor(823.4115999999999, shape=(), dtype=float64)


<tf.Tensor: shape=(), dtype=float64, numpy=28.695149415885602>

In [ ]:
tf.size(data)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

## 2022.06.11 - Tensorflow Fundamental 3

### Find the position of minimum and maximum
- easy to find the index of maximum and minimum then to label it or compare the predicted and actual value.

In [ ]:
data = tf.constant(np.random.randint(0,100,size=50).reshape(5,10)*1.0)
print(data.ndim)
print(data)

2
tf.Tensor(
[[32. 82. 50. 59. 38. 37. 75. 63. 51.  9.]
 [ 7. 73. 65. 74.  2. 99. 85. 96. 62.  4.]
 [46. 90. 33. 99. 10. 14. 21. 97. 99. 83.]
 [96. 28. 32. 85. 92. 46. 29.  0. 45. 21.]
 [55. 83. 82. 28. 94. 40. 92. 83. 85. 81.]], shape=(5, 10), dtype=float64)


In [ ]:
# tensor can be viewed as index to indexer the tensor
print(tf.argmax(data,axis=1))
print(tf.reduce_max(data,axis=1))
print(data[0,tf.argmax(data,axis=1)[0]] == tf.reduce_max(data,axis=1)[0])
print(tf.argmin(data,axis=1))
print(tf.reduce_min(data,axis=1))

tf.Tensor([1 5 3 0 4], shape=(5,), dtype=int64)
tf.Tensor([82. 99. 99. 96. 94.], shape=(5,), dtype=float64)
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor([9 4 4 7 3], shape=(5,), dtype=int64)
tf.Tensor([ 9.  2. 10.  0. 28.], shape=(5,), dtype=float64)


### Squeezing the tensors 
 - remove all dimensions that only include 1 element

In [ ]:
S = tf.constant(tf.random.uniform((1,1,1,1,50)))

In [ ]:
print(tf.squeeze(S))
tf.squeeze(S).shape[0]

tf.Tensor(
[0.01452792 0.5075201  0.76797616 0.1656152  0.02546835 0.6364001
 0.8997843  0.8040842  0.77213347 0.13624763 0.1498884  0.4364934
 0.0844574  0.09030998 0.3530562  0.5768864  0.12654746 0.9370935
 0.8868599  0.76716256 0.96796715 0.77701986 0.85111475 0.651001
 0.2557776  0.44316912 0.7672961  0.5624596  0.84120417 0.08463967
 0.5728135  0.37961614 0.45207953 0.28983366 0.4788066  0.24333942
 0.92461884 0.7918999  0.520617   0.9164723  0.56811404 0.24902582
 0.33135045 0.23262632 0.58611846 0.8747262  0.9306774  0.30738986
 0.09390843 0.31186438], shape=(50,), dtype=float32)


50

### One-hot encoding
- tf.one_hot

In [ ]:
some_list = range(0,4)

# on_value, the value match category, off_value. the value doesn't match the category
tf.one_hot(some_list,depth=3,on_value="Y",off_value="N")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'Y', b'N', b'N'],
       [b'N', b'Y', b'N'],
       [b'N', b'N', b'Y'],
       [b'N', b'N', b'N']], dtype=object)>

### More Math operations

In [ ]:
new_tensor = tf.range(10)

In [ ]:
print(tf.square(new_tensor))
print(tf.sqrt(tf.cast(new_tensor,dtype=tf.dtypes.float16)))
print(tf.math.log(tf.cast(new_tensor,dtype=tf.dtypes.float16)))

tf.Tensor([ 0  1  4  9 16 25 36 49 64 81], shape=(10,), dtype=int32)
tf.Tensor([0.    1.    1.414 1.732 2.    2.236 2.45  2.646 2.828 3.   ], shape=(10,), dtype=float16)
tf.Tensor([  -inf 0.     0.6934 1.099  1.387  1.609  1.792  1.946  2.08   2.197 ], shape=(10,), dtype=float16)


### Compatibility between numpy and tensorflow
- default dtype for floating point is different
  - numpy: float64
  - tensorflow: float32

In [ ]:
print(np.random.randn(10,10).dtype)
print(tf.random.normal(shape=[30]).dtype)

float64
<dtype: 'float32'>


In [ ]:
J = tf.constant(tf.range(30))
print(J.numpy())
np.array(J), type(np.array(J))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32),
 numpy.ndarray)

In [ ]:
JN = np.array(J)
tf.constant(JN),type(tf.constant(JN))

(<tf.Tensor: shape=(30,), dtype=int32, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>,
 tensorflow.python.framework.ops.EagerTensor)

### Run tensors on the GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
### test GPU is available
tf.test.is_gpu_available()
print(tf.config.list_physical_devices())
print(tf.config.list_physical_devices('GPU'))

# how to access GPU
tf.test.is_gpu_available()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


True

In [ ]:
#
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-affdb74e-10d5-a252-3c1c-24e6918d184b)


## Exercises
- Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

- Find the shape, rank and size of the tensors you created in 1.

- Create two tensors containing random values between 0 and 1 with shape [5, 300].

- Multiply the two tensors you created in 3 using matrix multiplication.

- Multiply the two tensors you created in 3 using dot product.

- Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

- Find the min and max values of the tensor you created in 6.

- Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

- Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

- One-hot encode the tensor you created in 9.




In [ ]:
scalar = tf.constant(10)
vector = tf.constant([10,10])
matrix = tf.constant(tf.reshape(tf.range(100),shape=(10,10)))
tensor = tf.ones(shape=(2,3,4,5))

In [ ]:
def show_info_tensor(tensor,name=None):
  name = "" if not name else name
  print(f"{name}: ")
  print(tensor.shape,tensor.ndim,tf.rank(tensor),tf.size(tensor))

show_info_tensor(scalar,"scalar")
show_info_tensor(vector,"vector")
show_info_tensor(matrix,"matrix")
show_info_tensor(tensor,"tensor")

scalar: 
() 0 tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)
vector: 
(2,) 1 tf.Tensor(1, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)
matrix: 
(10, 10) 2 tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(100, shape=(), dtype=int32)
tensor: 
(2, 3, 4, 5) 4 tf.Tensor(4, shape=(), dtype=int32) tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
tf.random.set_seed(50)
a_tensor = tf.random.normal([5,300])
b_tensor = tf.random.normal([5,300])

In [ ]:
tf.matmul(tf.transpose(a_tensor),b_tensor)
tf.tensordot(tf.transpose(a_tensor),b_tensor,axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[-7.1685386e+00,  1.1473501e-01,  2.1391706e-01, ...,
         7.6639962e+00, -4.3443861e+00,  1.3419929e+00],
       [-9.2797714e-01,  1.6624513e-01,  2.1163752e+00, ...,
        -1.9174743e+00,  1.2463714e+00,  2.4754250e-01],
       [-1.5128865e+00, -1.6340165e+00, -1.9666567e+00, ...,
         3.9334955e+00, -2.3893661e+00, -9.2074692e-01],
       ...,
       [-8.9702139e+00, -4.1398582e+00, -4.3142462e+00, ...,
         2.9283366e+00, -2.9221184e+00, -2.8664489e+00],
       [-5.0611815e+00, -9.6359462e-02, -1.4880518e+00, ...,
         1.5780725e+00, -1.9388225e+00, -1.0957892e+00],
       [-1.1637000e+01,  3.7710310e-03,  6.5080845e-01, ...,
         8.0707884e+00, -4.6435137e+00,  2.1087081e+00]], dtype=float32)>

In [ ]:
random_generator = tf.random.Generator.from_seed(20)
c_tensor = random_generator.uniform(shape = [1,224,224,3])
print(tf.math.reduce_max(c_tensor))
print(tf.math.reduce_min(c_tensor))
tf.squeeze(c_tensor).shape

tf.Tensor(0.99998736, shape=(), dtype=float32)
tf.Tensor(4.053116e-06, shape=(), dtype=float32)


TensorShape([224, 224, 3])

In [ ]:
np.random.seed(20)
choice_list = np.random.randint(1,10, size=10)
d_tensor = tf.constant(np.random.choice(choice_list,10),dtype=tf.dtypes.int32)
print(d_tensor)

print(tf.argmax(d_tensor))
print(tf.argmin(d_tensor))

tf.Tensor([4 7 7 4 4 1 9 1 7 7], shape=(10,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)


In [ ]:
max_shape = max(d_tensor.shape)
tf.one_hot(d_tensor,depth=max(max_shape,tf.math.reduce_max(d_tensor)))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>